import { Suspense } from 'react';
import { VerificationRequestsPage } from '@/components/Manager/Task-Verification/verification-request-page';
import type { VerificationRequest } from '@/types/manager-verification-req';
import { Sidebar } from '@/components/Manager/Task-Verification/sidebar';

// Temporary mock data (replace with Supabase query later)
const MOCK_REQUESTS: VerificationRequest[] = [
  {
    id: '1',
    date: new Date('2025-10-25T10:30:00'),
    employeeName: 'Carlos Mendoza',
    employeeId: 'E001',
    task: 'Project Documentation',
    repeat: 1,
    totalPoints: 5,
    status: 'pending',
  },
  {
    id: '2',
    date: new Date('2025-10-25T11:00:00'),
    employeeName: 'Angela Reyes',
    employeeId: 'E002',
    task: 'Client Presentation',
    repeat: 2,
    totalPoints: 10,
    status: 'pending',
  },
  {
    id: '3',
    date: new Date('2025-10-25T13:15:00'),
    employeeName: 'Mark Villanueva',
    employeeId: 'E003',
    task: 'System Testing',
    repeat: 3,
    totalPoints: 15,
    status: 'pending',
  },
  {
    id: '4',
    date: new Date('2025-10-25T14:45:00'),
    employeeName: 'Sophia Cruz',
    employeeId: 'E004',
    task: 'Knowledge Sharing Session',
    repeat: 1,
    totalPoints: 8,
    status: 'pending',
  },
  {
    id: '5',
    date: new Date('2025-10-25T15:30:00'),
    employeeName: 'Daniel Santos',
    employeeId: 'E005',
    task: 'Customer Support Ticket',
    repeat: 4,
    totalPoints: 12,
    status: 'pending',
  },
  {
    id: '6',
    date: new Date('2025-10-25T16:00:00'),
    employeeName: 'Emily Tan',
    employeeId: 'E006',
    task: 'Process Improvement Proposal',
    repeat: 2,
    totalPoints: 9,
    status: 'pending',
  },
  {
    id: '7',
    date: new Date('2025-10-24T10:30:00'),
    employeeName: 'Miguel Ramos',
    employeeId: 'E007',
    task: 'Team Workshop Facilitation',
    repeat: 1,
    totalPoints: 7,
    status: 'approved',
  },
  {
    id: '8',
    date: new Date('2025-10-24T09:15:00'),
    employeeName: 'Hannah Lee',
    employeeId: 'E008',
    task: 'Data Entry Audit',
    repeat: 2,
    totalPoints: 6,
    status: 'denied',
  },
  {
    id: '9',
    date: new Date('2025-10-23T14:00:00'),
    employeeName: 'Robert Cruz',
    employeeId: 'E009',
    task: 'Weekly Report Submission',
    repeat: 1,
    totalPoints: 5,
    status: 'approved',
  },
  {
    id: '10',
    date: new Date('2025-10-23T15:30:00'),
    employeeName: 'Isabella Flores',
    employeeId: 'E010',
    task: 'Client Survey Analysis',
    repeat: 1,
    totalPoints: 10,
    status: 'pending',
  },
  {
    id: '11',
    date: new Date('2025-10-22T09:45:00'),
    employeeName: 'Joshua Lim',
    employeeId: 'E011',
    task: 'Bug Fix Deployment',
    repeat: 2,
    totalPoints: 12,
    status: 'approved',
  },
  {
    id: '12',
    date: new Date('2025-10-22T11:20:00'),
    employeeName: 'Patricia Gomez',
    employeeId: 'E012',
    task: 'Training Material Preparation',
    repeat: 1,
    totalPoints: 8,
    status: 'denied',
  },
  {
    id: '13',
    date: new Date('2025-10-21T13:00:00'),
    employeeName: 'Kevin Torres',
    employeeId: 'E013',
    task: 'Meeting Facilitation',
    repeat: 1,
    totalPoints: 6,
    status: 'pending',
  },
  {
    id: '14',
    date: new Date('2025-10-21T14:30:00'),
    employeeName: 'Andrea Morales',
    employeeId: 'E014',
    task: 'Knowledge Base Update',
    repeat: 2,
    totalPoints: 9,
    status: 'approved',
  },
  {
    id: '15',
    date: new Date('2025-10-20T10:00:00'),
    employeeName: 'Victor Hernandez',
    employeeId: 'E015',
    task: 'Performance Review Draft',
    repeat: 1,
    totalPoints: 7,
    status: 'pending',
  },
  // --- Additional mock entries up to 50 ---
  {
    id: '16',
    date: new Date('2025-10-19T09:00:00'),
    employeeName: 'Laura Kim',
    employeeId: 'E016',
    task: 'Market Research',
    repeat: 2,
    totalPoints: 10,
    status: 'approved',
  },
  {
    id: '17',
    date: new Date('2025-10-19T11:30:00'),
    employeeName: 'Steven Yu',
    employeeId: 'E017',
    task: 'Code Review',
    repeat: 3,
    totalPoints: 12,
    status: 'denied',
  },
  {
    id: '18',
    date: new Date('2025-10-18T14:00:00'),
    employeeName: 'Grace Park',
    employeeId: 'E018',
    task: 'UI Design Update',
    repeat: 1,
    totalPoints: 8,
    status: 'pending',
  },
  {
    id: '19',
    date: new Date('2025-10-18T15:45:00'),
    employeeName: 'Anthony Lopez',
    employeeId: 'E019',
    task: 'Database Migration',
    repeat: 2,
    totalPoints: 14,
    status: 'approved',
  },
  {
    id: '20',
    date: new Date('2025-10-17T09:30:00'),
    employeeName: 'Natalie Chen',
    employeeId: 'E020',
    task: 'Security Audit',
    repeat: 1,
    totalPoints: 11,
    status: 'pending',
  },
  {
    id: '21',
    date: new Date('2025-10-17T10:15:00'),
    employeeName: 'Brian Scott',
    employeeId: 'E021',
    task: 'Content Writing',
    repeat: 4,
    totalPoints: 16,
    status: 'approved',
  },
  {
    id: '22',
    date: new Date('2025-10-16T13:00:00'),
    employeeName: 'Olivia Perez',
    employeeId: 'E022',
    task: 'Customer Demo',
    repeat: 1,
    totalPoints: 7,
    status: 'denied',
  },
  {
    id: '23',
    date: new Date('2025-10-16T14:30:00'),
    employeeName: 'Jason Wu',
    employeeId: 'E023',
    task: 'API Integration',
    repeat: 2,
    totalPoints: 12,
    status: 'pending',
  },
  {
    id: '24',
    date: new Date('2025-10-15T09:45:00'),
    employeeName: 'Megan Smith',
    employeeId: 'E024',
    task: 'Recruitment Interview',
    repeat: 1,
    totalPoints: 6,
    status: 'approved',
  },
  {
    id: '25',
    date: new Date('2025-10-15T11:00:00'),
    employeeName: 'David Johnson',
    employeeId: 'E025',
    task: 'Budget Planning',
    repeat: 3,
    totalPoints: 15,
    status: 'pending',
  },
  {
    id: '26',
    date: new Date('2025-10-14T10:30:00'),
    employeeName: 'Rachel Green',
    employeeId: 'E026',
    task: 'Social Media Campaign',
    repeat: 2,
    totalPoints: 9,
    status: 'approved',
  },
  {
    id: '27',
    date: new Date('2025-10-14T12:00:00'),
    employeeName: 'Chris Evans',
    employeeId: 'E027',
    task: 'Server Maintenance',
    repeat: 1,
    totalPoints: 10,
    status: 'denied',
  },
    {
    id: '28',
    date: new Date('2025-10-13T09:00:00'),
    employeeName: 'Liam Martinez',
    employeeId: 'E028',
    task: 'Performance Metrics Review',
    repeat: 1,
    totalPoints: 8,
    status: 'pending',
  },
  {
    id: '29',
    date: new Date('2025-10-13T11:15:00'),
    employeeName: 'Sophia Johnson',
    employeeId: 'E029',
    task: 'Employee Onboarding',
    repeat: 2,
    totalPoints: 12,
    status: 'approved',
  },
  {
    id: '30',
    date: new Date('2025-10-12T14:30:00'),
    employeeName: 'Ethan Brown',
    employeeId: 'E030',
    task: 'System Backup',
    repeat: 1,
    totalPoints: 10,
    status: 'denied',
  },
  {
    id: '31',
    date: new Date('2025-10-12T15:45:00'),
    employeeName: 'Ava Wilson',
    employeeId: 'E031',
    task: 'Client Call Follow-up',
    repeat: 3,
    totalPoints: 9,
    status: 'pending',
  },
  {
    id: '32',
    date: new Date('2025-10-11T09:20:00'),
    employeeName: 'Noah Anderson',
    employeeId: 'E032',
    task: 'Inventory Check',
    repeat: 2,
    totalPoints: 7,
    status: 'approved',
  },
  {
    id: '33',
    date: new Date('2025-10-11T10:50:00'),
    employeeName: 'Mia Thompson',
    employeeId: 'E033',
    task: 'Policy Drafting',
    repeat: 1,
    totalPoints: 11,
    status: 'denied',
  },
  {
    id: '34',
    date: new Date('2025-10-10T13:00:00'),
    employeeName: 'James White',
    employeeId: 'E034',
    task: 'Workshop Attendance',
    repeat: 2,
    totalPoints: 6,
    status: 'pending',
  },
  {
    id: '35',
    date: new Date('2025-10-10T14:30:00'),
    employeeName: 'Olivia Harris',
    employeeId: 'E035',
    task: 'Marketing Strategy Proposal',
    repeat: 1,
    totalPoints: 10,
    status: 'approved',
  },
  {
    id: '36',
    date: new Date('2025-10-09T09:45:00'),
    employeeName: 'William Clark',
    employeeId: 'E036',
    task: 'Code Deployment',
    repeat: 2,
    totalPoints: 14,
    status: 'denied',
  },
  {
    id: '37',
    date: new Date('2025-10-09T11:00:00'),
    employeeName: 'Emma Lewis',
    employeeId: 'E037',
    task: 'Client Feedback Review',
    repeat: 1,
    totalPoints: 9,
    status: 'pending',
  },
  {
    id: '38',
    date: new Date('2025-10-08T13:15:00'),
    employeeName: 'Benjamin Walker',
    employeeId: 'E038',
    task: 'Server Optimization',
    repeat: 3,
    totalPoints: 15,
    status: 'approved',
  },
  {
    id: '39',
    date: new Date('2025-10-08T14:45:00'),
    employeeName: 'Charlotte Hall',
    employeeId: 'E039',
    task: 'Training Session',
    repeat: 1,
    totalPoints: 7,
    status: 'denied',
  },
  {
    id: '40',
    date: new Date('2025-10-07T09:30:00'),
    employeeName: 'Lucas Allen',
    employeeId: 'E040',
    task: 'Documentation Update',
    repeat: 2,
    totalPoints: 8,
    status: 'pending',
  },
  {
    id: '41',
    date: new Date('2025-10-07T11:00:00'),
    employeeName: 'Amelia Young',
    employeeId: 'E041',
    task: 'Recruitment Drive',
    repeat: 1,
    totalPoints: 12,
    status: 'approved',
  },
  {
    id: '42',
    date: new Date('2025-10-06T13:00:00'),
    employeeName: 'Henry King',
    employeeId: 'E042',
    task: 'Financial Audit',
    repeat: 2,
    totalPoints: 14,
    status: 'denied',
  },
  {
    id: '43',
    date: new Date('2025-10-06T14:30:00'),
    employeeName: 'Ella Wright',
    employeeId: 'E043',
    task: 'Team Building Activity',
    repeat: 1,
    totalPoints: 6,
    status: 'pending',
  },
  {
    id: '44',
    date: new Date('2025-10-05T09:15:00'),
    employeeName: 'Alexander Green',
    employeeId: 'E044',
    task: 'System Monitoring',
    repeat: 3,
    totalPoints: 13,
    status: 'approved',
  },
  {
    id: '45',
    date: new Date('2025-10-05T10:45:00'),
    employeeName: 'Harper Baker',
    employeeId: 'E045',
    task: 'Content Editing',
    repeat: 2,
    totalPoints: 9,
    status: 'denied',
  },
  {
    id: '46',
    date: new Date('2025-10-04T13:00:00'),
    employeeName: 'Daniel Carter',
    employeeId: 'E046',
    task: 'Bug Tracking',
    repeat: 1,
    totalPoints: 8,
    status: 'pending',
  },
  {
    id: '47',
    date: new Date('2025-10-04T14:30:00'),
    employeeName: 'Sofia Rivera',
    employeeId: 'E047',
    task: 'Client Proposal Draft',
    repeat: 2,
    totalPoints: 11,
    status: 'approved',
  },
  {
    id: '48',
    date: new Date('2025-10-03T09:45:00'),
    employeeName: 'Matthew Torres',
    employeeId: 'E048',
    task: 'System Upgrade',
    repeat: 1,
    totalPoints: 10,
    status: 'denied',
  },
  {
    id: '49',
    date: new Date('2025-10-03T11:00:00'),
    employeeName: 'Chloe Ramirez',
    employeeId: 'E049',
    task: 'Workshop Facilitation',
    repeat: 2,
    totalPoints: 7,
    status: 'pending',
  },
  {
    id: '50',
    date: new Date('2025-10-02T13:15:00'),
    employeeName: 'Jack Foster',
    employeeId: 'E050',
    task: 'Performance Evaluation',
    repeat: 1,
    totalPoints: 12,
    status: 'approved',
  },
];


export default async function Manager() {
  // Later: const requests = await supabase.from('verification_requests').select('*');
  const requests = MOCK_REQUESTS;

  return (
    <Suspense>
      <div className="flex h-screen bg-gray-100">
        <Sidebar />
        <main className="flex-1 overflow-auto">
          <VerificationRequestsPage initialRequests={requests} />
        </main>
      </div>
    </Suspense>
  );
}
