/**
 * Employee Statistics Actions
 * 
 * This file contains all employee stat getter functions:
 * - getEmployeeLevel: Fetches the current employee's level
 * - getEmployeePoints: Fetches points and deducted points
 * - getEmployeePerformanceScore: Fetches performance_score (approved task count × total_points_earned)
 * - getEmployeeRank: Fetches rank among all employees
 * - getEmployeeXP: Fetches current and total XP
 */

'use server';

import { createClient } from '@/lib/supabase/server';
import { supabaseAdmin } from '@/lib/supabase/admin';
import { safeAction, type ActionResult } from '@/lib/utils/safe-action';
import { getPeriodStartEnd } from '@/lib/utils/time-period-utils';
import { format } from 'date-fns';
import type {
  EmployeeRank,
  EmployeeTopRankEntry,
  EmployeeXP,
  RankLogPeriodType,
} from '@/types';

export interface EmployeePointsData {
  points: number;
  deductedPoints: number;
}

export async function getEmployeeLevel(): Promise<ActionResult<number>> {
  return safeAction(async () => {
    const supabase = await createClient();

    const {
      data: { user },
      error: userError,
    } = await supabase.auth.getUser();

    if (userError || !user) {
      throw new Error('User not authenticated');
    }

    const { data, error } = await supabase
      .from('user_attributes')
      .select('user_level')
      .eq('user_id', user.id)
      .single();

    if (error) {
      throw new Error(`Failed to fetch user level: ${error.message}`);
    }

    if (!data) {
      throw new Error('User level data not found');
    }

    return data.user_level ?? 1;
  });
}

export async function getEmployeePoints(): Promise<ActionResult<EmployeePointsData>> {
  return safeAction(async () => {
    const supabase = await createClient();

    const {
      data: { user },
      error: userError,
    } = await supabase.auth.getUser();

    if (userError || !user) {
      throw new Error('User not authenticated');
    }

    const { data, error } = await supabaseAdmin
      .from('User')
      .select('points, deducted_points')
      .eq('id', user.id)
      .single();

    if (error) {
      throw new Error(`Failed to fetch user points: ${error.message}`);
    }

    if (!data) {
      throw new Error('User points data not found');
    }

    return {
      points: data.points ?? 0,
      deductedPoints: data.deducted_points ?? 0,
    };
  });
}

/**
 * Fetches the current employee's performance score from user_attributes.
 * performance_score = (count of approved KPITask) × total_points_earned (used for leaderboard ranking).
 */
export async function getEmployeePerformanceScore(): Promise<ActionResult<number>> {
  return safeAction(async () => {
    const supabase = await createClient();

    const {
      data: { user },
      error: userError,
    } = await supabase.auth.getUser();

    if (userError || !user) {
      throw new Error('User not authenticated');
    }

    const { data, error } = await supabase
      .from('user_attributes')
      .select('performance_score')
      .eq('user_id', user.id)
      .single();

    if (error) {
      throw new Error(`Failed to fetch performance score: ${error.message}`);
    }

    if (!data) {
      return 0;
    }

    return Number(data.performance_score ?? 0);
  });
}

/**
 * Fetches the latest weekly rank snapshot for the current employee.
 * Ranking is generated by HR and stored in RankingPeriod + RankingEntry.
 * Only shows data when the latest week (by period_start) exists and is_visible = true;
 * if the latest week is hidden, returns placeholder so the UI shows "Not available yet".
 * Uses admin client to read period visibility (RLS would otherwise hide non-visible periods).
 */
export async function getEmployeeRank(): Promise<ActionResult<EmployeeRank>> {
  return safeAction(async () => {
    const supabase = await createClient();

    const {
      data: { user },
      error: userError,
    } = await supabase.auth.getUser();

    if (userError || !user) {
      throw new Error('User not authenticated');
    }

    // only return visible periods, so we'd always get the latest *visible* (previous) week.
    const { data: latestPeriod, error: periodError } = await supabaseAdmin
      .from('RankingPeriod')
      .select('id, is_visible')
      .eq('period_type', 'weekly')
      .order('period_start', { ascending: false })
      .limit(1)
      .maybeSingle();

    if (periodError) {
      throw new Error(`Failed to fetch ranking period: ${periodError.message}`);
    }

    // No weekly ranking exists yet, or latest week is hidden — show "Not available yet"
    if (!latestPeriod || !latestPeriod.is_visible) {
      return {
        rank: 1,
        performanceScore: 0,
        totalEmployees: 1,
      };
    }

    //  Fetch all entries for this period 
    const { data: allEntries, error: allEntriesError } = await supabaseAdmin
      .from('RankingEntry')
      .select('user_id, rank, performance_score')
      .eq('ranking_period_id', latestPeriod.id);

    if (allEntriesError) {
      throw new Error(`Failed to fetch ranking entries: ${allEntriesError.message}`);
    }

    if (!allEntries || allEntries.length === 0) {
      return {
        rank: 1,
        performanceScore: 0,
        totalEmployees: 1,
      };
    }

    // Step 3: Find the current user's entry
    const userEntry = allEntries.find((entry) => entry.user_id === user.id);

    return {
      rank: userEntry?.rank ?? allEntries.length + 1,
      performanceScore: Number(userEntry?.performance_score ?? 0),
      totalEmployees: allEntries.length,
    };
  });
}

/**
 * Fetches the top 10 weekly rankings for the latest week that HR generated.
 * Uses the same "latest weekly period" as HR (RankingPeriod), then returns
 * entries only when that period is visible to employees.
 * Returns null when no visible weekly ranking exists for the latest period.
 */
export async function getEmployeeTopWeeklyRanks(): Promise<
  ActionResult<EmployeeTopRankEntry[] | null>
> {
  return safeAction(async () => {
    const supabase = await createClient();

    const {
      data: { user },
      error: userError,
    } = await supabase.auth.getUser();

    if (userError || !user) {
      throw new Error('User not authenticated');
    }

    // Use same source as HR: latest weekly period from RankingPeriod (the week HR generated)
    const { data: latestPeriod, error: periodError } = await supabaseAdmin
      .from('RankingPeriod')
      .select('period_start')
      .eq('period_type', 'weekly')
      .order('period_start', { ascending: false })
      .limit(1)
      .maybeSingle();

    if (periodError) {
      throw new Error(`Failed to fetch latest ranking period: ${periodError.message}`);
    }

    if (!latestPeriod?.period_start) {
      return null;
    }

    const periodStart = latestPeriod.period_start;

    // Fetch top 10 for that period only when it is visible to employees
    const { data: rows, error: rowsError } = await supabaseAdmin
      .from('ranking_leaderboard_view')
      .select('user_id, user_name, rank, performance_score')
      .eq('period_type', 'weekly')
      .eq('is_visible', true)
      .eq('period_start', periodStart)
      .order('rank', { ascending: true })
      .limit(10);

    if (rowsError) {
      throw new Error(`Failed to fetch ranking entries: ${rowsError.message}`);
    }

    if (!rows || rows.length === 0) {
      return null;
    }

    const result: EmployeeTopRankEntry[] = rows.map((row) => {
      const { data: urlData } = supabaseAdmin.storage
        .from('employees')
        .getPublicUrl(`${row.user_id}/profile.png`);
      return {
        rank: row.rank,
        userId: row.user_id ?? '',
        name: row.user_name ?? '',
        performanceScore: Number(row.performance_score ?? 0),
        isCurrentUser: row.user_id === user.id,
        profilePictureUrl: urlData?.publicUrl ?? null,
      };
    });

    return result;
  });
}

/**
 * Fetches the top 10 rankings for a specific period (weekly, monthly, or yearly).
 * Only returns data when that period exists and is visible to employees.
 */
export async function getEmployeeTopRanksByPeriod(
  periodType: RankLogPeriodType,
  year: number,
  month?: number,
  week?: number
): Promise<ActionResult<EmployeeTopRankEntry[] | null>> {
  return safeAction(async () => {
    const supabase = await createClient();

    const {
      data: { user },
      error: userError,
    } = await supabase.auth.getUser();

    if (userError || !user) {
      throw new Error('User not authenticated');
    }

    const { start } = getPeriodStartEnd(
      periodType,
      year,
      periodType === 'monthly' ? month : undefined,
      periodType === 'weekly' ? week : undefined
    );
    const periodStart = format(start, 'yyyy-MM-dd');

    const { data: rows, error: rowsError } = await supabaseAdmin
      .from('ranking_leaderboard_view')
      .select('user_id, user_name, rank, performance_score')
      .eq('period_type', periodType)
      .eq('is_visible', true)
      .eq('period_start', periodStart)
      .order('rank', { ascending: true })
      .limit(10);

    if (rowsError) {
      throw new Error(`Failed to fetch ranking entries: ${rowsError.message}`);
    }

    if (!rows || rows.length === 0) {
      return null;
    }

    const result: EmployeeTopRankEntry[] = rows.map((row) => {
      const { data: urlData } = supabaseAdmin.storage
        .from('employees')
        .getPublicUrl(`${row.user_id}/profile.png`);
      return {
        rank: row.rank,
        userId: row.user_id ?? '',
        name: row.user_name ?? '',
        performanceScore: Number(row.performance_score ?? 0),
        isCurrentUser: row.user_id === user.id,
        profilePictureUrl: urlData?.publicUrl ?? null,
      };
    });

    return result;
  });
}

export async function getEmployeeXP(): Promise<ActionResult<EmployeeXP>> {
  return safeAction(async () => {
    const supabase = await createClient();

    const {
      data: { user },
      error: userError,
    } = await supabase.auth.getUser();

    if (userError || !user) {
      throw new Error('User not authenticated');
    }

    const { data, error } = await supabase
      .from('user_attributes')
      .select('xp, user_level')
      .eq('user_id', user.id)
      .single();

    if (error) {
      throw new Error(`Failed to fetch user XP: ${error.message}`);
    }

    if (!data) {
      throw new Error('User XP data not found');
    }

    // Default level to 1 if null or 0
    const level = data.user_level && data.user_level > 0 ? data.user_level : 1;
    const currentXP = data.xp ?? 0;

    // totalXP counts cumulative XP including previous levels
    const totalXP = (level - 1) * 100 + currentXP;

    return {
      currentXP,
      totalXP,
      level,
    };
  });
}