export const managerTaskAssignmentIntegrationNames = {
  load: {
    managerNamePrefix: 'Task Assignment Load Manager',
    managerEmailPrefix: 'task.assignment.load.manager',
    employeeOneNamePrefix: 'Task Assignment Load Employee One',
    employeeOneEmailPrefix: 'task.assignment.load.employee.one',
    employeeTwoNamePrefix: 'Task Assignment Load Employee Two',
    employeeTwoEmailPrefix: 'task.assignment.load.employee.two',
    employeeIdPrefix: 'TASK-LOAD-EMP',
    hrNamePrefix: 'Task Assignment Load HR',
    hrEmailPrefix: 'task.assignment.load.hr',
    categoryOneNamePrefix: 'Task Assignment Load Category One',
    categoryTwoNamePrefix: 'Task Assignment Load Category Two',
  },
  assign: {
    managerNamePrefix: 'Task Assignment Create Manager',
    managerEmailPrefix: 'task.assignment.create.manager',
    employeeOneNamePrefix: 'Task Assignment Create Employee One',
    employeeOneEmailPrefix: 'task.assignment.create.employee.one',
    employeeTwoNamePrefix: 'Task Assignment Create Employee Two',
    employeeTwoEmailPrefix: 'task.assignment.create.employee.two',
    employeeIdPrefix: 'TASK-CREATE-EMP',
    categoryNamePrefix: 'Task Assignment Create Category',
  },
  partial: {
    managerNamePrefix: 'Task Assignment Partial Manager',
    managerEmailPrefix: 'task.assignment.partial.manager',
    busyEmployeeNamePrefix: 'Task Assignment Partial Busy Employee',
    busyEmployeeEmailPrefix: 'task.assignment.partial.busy',
    freeEmployeeNamePrefix: 'Task Assignment Partial Free Employee',
    freeEmployeeEmailPrefix: 'task.assignment.partial.free',
    employeeIdPrefix: 'TASK-PARTIAL-EMP',
    categoryNamePrefix: 'Task Assignment Partial Category',
  },
  allBusy: {
    managerNamePrefix: 'Task Assignment All Busy Manager',
    managerEmailPrefix: 'task.assignment.all.busy.manager',
    employeeOneNamePrefix: 'Task Assignment All Busy Employee One',
    employeeOneEmailPrefix: 'task.assignment.all.busy.employee.one',
    employeeTwoNamePrefix: 'Task Assignment All Busy Employee Two',
    employeeTwoEmailPrefix: 'task.assignment.all.busy.employee.two',
    employeeIdPrefix: 'TASK-ALL-BUSY-EMP',
    categoryNamePrefix: 'Task Assignment All Busy Category',
  },
};
